### ISSUE TITLE
Problem with the '^' operator

### ISSUE THREAD

**Issue by a3nm** [PoDMR/enum-spanner-rs#2]
Hi,

I have the following problem with the '^' operator:

```
$ echo BA | RUST_BACKTRACE=1 cargo run --release -- -b '^A' 
                                                                
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/enum-spanner-rs -b '^A'`
⠁ [=========================================]  00:00  390.62 Ki/s
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 18446744073709551615', src/mapping/levelset.rs:60:36
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   9: enum_spanner_rs::mapping::levelset::LevelSet::get_level
  10: enum_spanner_rs::mapping::levelset::LevelSet::keep_only
  11: enum_spanner_rs::mapping::jump::Jump::trim_level
  12: <enum_spanner_rs::mapping::indexed_dag::IndexedDag<'t> as enum_spanner_rs::mapping::SpannerEnumerator<'t>>::preprocess
  13: enum_spanner_rs::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  17: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by niewerth** [comment]
There is an optimization that aborts the preprocessing as soon, as it is obvious that there cannot be any matches. Actually this optimization can only trigger in case of an ^-anchor, as otherwise it is always possible to have a matching somewhere later in the input. 

There was a bug, such that the later preprocessing steps (especially going backwards to prune states that are not used in any match) are performed even if the DAG is only partly constructed. This backwards pass crashed in case of a partly constructed DAG. Now, also the later preprocessing steps are skipped in case of a partly constructed DAG.

**Comment by a3nm** [comment]
Yes, now it works for me as well -- thanks!
